//autogenerated file, don't try to change something manually
#pragma once
#include <string>
#include "Strings.h"

namespace R {
extern const std::string DIR_NAME;
namespace UiNight {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
namespace Dialogs {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string REMOVE_ADS;
extern const std::string BUTTON_TRANSPARENT;
extern const std::string RATE_DIALOG;
extern const std::string CHECKBOX;
extern const std::string SKIP_WITH_OPTIONS;
extern const std::string PAUSE_DIALOG;
extern const std::string SKIP_FOR_SKIP;
extern const std::string SKIP_FOR_VIDEO;
extern const std::string BODY_BACKGROUND;
extern const std::string SKIP_WITH_OPTIONS_AND_CROSS_PROMO;
extern const std::string APP_TURBO;
extern const std::string STARS;
extern const std::string SKIP_OPTION_BUTTON;
extern const std::string CROSS_PROMO_DIALOG;
extern const std::string BUTTON;
extern const std::string EXIT_CONFIRMATION_DIALOG;
extern const std::string SETTINGS;
extern const std::string CROSS_PROMO_DIALOG_BUTTON;
} //Dialogs
namespace Support {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string LOADING_INDICATOR;
extern const std::string PROGRESS_HUD;
} //Support
namespace Share {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string BULLET;
extern const std::string SHARE_BANNER;
} //Share
namespace MainMenu {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string SCENE;
extern const std::string ROUND_BUTTON;
extern const std::string BACKGROUND;
extern const std::string PLAY_BUTTON_ANIMATED_BACKGROUND;
extern const std::string SCENE_TABLET;
extern const std::string BOTTOM_BUTTONS_ANDROID;
extern const std::string BLACK_ROUND_BUTTON;
extern const std::string PLAY_BUTTON_BACKGROUND;
extern const std::string FRAME_BUTTON;
extern const std::string BACK_BUTTON;
extern const std::string BOTTOM_BUTTONS;
extern const std::string PLAY_BUTTON;
} //MainMenu
namespace Game {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string CENTRAL_NODE;
extern const std::string SECOND_CHANCE_ALERT;
extern const std::string SCENE;
extern const std::string START_LEVEL_HINT;
extern const std::string HEART;
extern const std::string BULLET;
} //Game
namespace LevelSelection {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string LEVEL_ITEM;
extern const std::string BACK_BUTTON;
extern const std::string SCENE;
} //LevelSelection
} //UiNight
extern const std::string COLOR_SCHEME_PLIST;
extern const std::string FILE_LOOKUP_PLIST;
namespace Localization {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
namespace ru {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //ru
namespace fr {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //fr
namespace en {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //en
namespace nl {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //nl
namespace pt {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //pt
namespace de {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //de
namespace ko {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //ko
namespace it {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //it
namespace zh {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //zh
namespace ja {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //ja
namespace es {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string STRINGS_PLIST;
} //es
} //Localization
namespace Fonts {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string HELVETICA_NEUE_LIGHT;
extern const std::string HELVETICA_NEUE_BOLD;
extern const std::string HELVETICA_NEUE_ROMAN;
extern const std::string HELVETICA_NEUE_MEDIUM;
extern const std::string HELVETICA_NEUE_ULTRA_LIGHT;
} //Fonts
namespace SampleLevels {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string S3;
extern const std::string S1;
extern const std::string S4;
extern const std::string LEVEL_TEMPLATE;
extern const std::string R190;
extern const std::string R193;
extern const std::string R195;
extern const std::string R198;
extern const std::string R188;
extern const std::string R186;
extern const std::string R184;
extern const std::string R200;
extern const std::string R199;
extern const std::string INVERSE;
extern const std::string S2;
extern const std::string R194;
} //SampleLevels
extern const std::string APP_SETTINGS_IOS;
namespace UI {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
namespace Dialogs {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string REMOVE_ADS;
extern const std::string BUTTON_TRANSPARENT;
extern const std::string RATE_DIALOG;
extern const std::string CHECKBOX;
extern const std::string SKIP_WITH_OPTIONS;
extern const std::string PAUSE_DIALOG;
extern const std::string SKIP_FOR_SKIP;
extern const std::string SKIP_FOR_VIDEO;
extern const std::string BODY_BACKGROUND;
extern const std::string SKIP_WITH_OPTIONS_AND_CROSS_PROMO;
extern const std::string APP_TURBO;
extern const std::string STARS;
extern const std::string SKIP_OPTION_BUTTON;
extern const std::string CROSS_PROMO_DIALOG;
extern const std::string BUTTON;
extern const std::string EXIT_CONFIRMATION_DIALOG;
extern const std::string SETTINGS;
extern const std::string CROSS_PROMO_DIALOG_BUTTON;
} //Dialogs
namespace Support {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string LOADING_INDICATOR;
extern const std::string PROGRESS_HUD;
} //Support
namespace Share {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string BULLET;
extern const std::string SHARE_BANNER;
} //Share
namespace MainMenu {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string SCENE;
extern const std::string ROUND_BUTTON;
extern const std::string BACKGROUND;
extern const std::string PLAY_BUTTON_ANIMATED_BACKGROUND;
extern const std::string SCENE_TABLET;
extern const std::string BOTTOM_BUTTONS_ANDROID;
extern const std::string BLACK_ROUND_BUTTON;
extern const std::string PLAY_BUTTON_BACKGROUND;
extern const std::string FRAME_BUTTON;
extern const std::string BACK_BUTTON;
extern const std::string BOTTOM_BUTTONS;
extern const std::string PLAY_BUTTON;
} //MainMenu
namespace Game {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string CENTRAL_NODE;
extern const std::string SECOND_CHANCE_ALERT;
extern const std::string SCENE;
extern const std::string START_LEVEL_HINT;
extern const std::string HEART;
extern const std::string BULLET;
} //Game
namespace LevelSelection {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string LEVEL_ITEM;
extern const std::string BACK_BUTTON;
extern const std::string SCENE;
} //LevelSelection
} //UI
namespace Shaders {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string SHADER_CIRCLE_FRAG;
extern const std::string SHADER_SHADOWED_CIRCLE_FRAG;
extern const std::string SHADER_COLOR_REPLACEMENT_NO_MVP_FRAG;
extern const std::string SHADER_COLOR_REPLACEMENT_NO_MVP_VERT;
extern const std::string SHADER_CIRCLE_VERT;
} //Shaders
namespace Images {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
namespace Dialogs {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string TWITTER_IMG;
extern const std::string VKONTAKTE_IMG;
extern const std::string FACEBOOK_IMG;
extern const std::string INVITE_FRIENDS_IMG;
extern const std::string WATCH_VIDEO_IMG;
} //Dialogs
namespace Unscaled {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string BACKGROUND_IMG;
} //Unscaled
namespace Menu {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string SETTINGS_IMG;
extern const std::string PLAY_BUTTON_SHADOW_IMG;
extern const std::string SHARE_IMG;
extern const std::string ROUND_BUTTON_BACKGROUND_IMG;
extern const std::string PLAY_BUTTON_BACKGROUND_IMG;
extern const std::string PLAY_BUTTON_IMG;
extern const std::string BACK_BUTTON_IMG;
extern const std::string TWITTER_IMG;
extern const std::string GOOGLE_GAMEPAD_IMG;
extern const std::string LEADERBOARD_ANDROID_IMG;
extern const std::string LEADERBOARD_IMG;
extern const std::string FACEBOOK_IMG;
extern const std::string SOUND_ON_IMG;
extern const std::string RATE_IMG;
extern const std::string NO_ADS_IMG;
extern const std::string SOUND_OFF_IMG;
extern const std::string ACHIEVEMENTS_ANDROID_IMG;
} //Menu
namespace Support {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string TOGGLE_BALL_IMG;
extern const std::string SQUARE_8_IMG;
extern const std::string FRAMED_RECT_IMG;
extern const std::string CROSS_IMG;
extern const std::string CIRCLE_IMG;
extern const std::string STAR_IMG;
extern const std::string TOGGLE_BACKGROUND_IMG;
extern const std::string ROUNDED_RECTANGLE_IMG;
extern const std::string VERY_ROUNDED_RECTANGLE_IMG;
extern const std::string CHECK_IMG;
} //Support
namespace Share {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string SHARE_TEMPLATE_DARK_IMG;
extern const std::string BULLET_IMG;
extern const std::string SHARE_TEMPLATE_IMG;
} //Share
namespace Game {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string HEART_IMG;
extern const std::string BULLET_IMG;
extern const std::string CENTRAL_NODE_IMG;
} //Game
} //Images
extern const std::string APP_SETTINGS_ANDROID;
namespace Audio {
extern const std::string DIR_NAME;
extern const std::string DIR_PATH;
extern const std::string TAP;
extern const std::string WIN;
extern const std::string BUTTON;
extern const std::string LOSE;
extern const std::string MUSIC;
} //Audio
extern const std::string IA_PURCHASES_PLIST;
} //R
namespace R {
	extern const int LEVELS_COUNT;
}