platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'Pulp'
project 'Pulp.xcodeproj'

def appPods
  pod 'RMStore'
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'VK-ios-sdk', '~>1.3.17'

  pod 'Tune'
  
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/RemoteConfig'
  
  pod 'FBAudienceNetwork'
  pod 'VungleSDK-iOS'
  pod 'UnityAds'
  
end

target 'Pulp-mobile' do
  appPods
end

target 'Dulp-mobile-Nexx' do
  appPods
end
